services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: converso-whatsapp-api-cloudflare-tunnel
    hostname: converso-whatsapp-api-connector
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARES_TOKEN}
    env_file:
      - ./.env
    networks:
      - converso-whatsapp-api-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: converso-whatsapp-api-host
    restart: always
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - converso-whatsapp-api-network
    depends_on:
      - api

  api:
    container_name: converso-whatsapp-api
    build:
      context: .
      dockerfile: Dockerfile
    image: converso-whatsapp-api:local
    restart: always
    depends_on:
      redis:
        condition: service_started
    volumes:
      - converso-whatsapp-api_instances:/converso-whatsapp-api/instances
    networks:
      - converso-whatsapp-api-network
    env_file:
      - .env
    expose:
      - "7871"

  redis:
    container_name: converso-whatsapp-api_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - converso-whatsapp-api_redis:/data
    networks:
      converso-whatsapp-api-network:
        aliases:
          - converso-whatsapp-api-redis
    expose:
      - "6379"

  converso-whatsapp-api-postgres:
    container_name: converso-whatsapp-api_postgres
    image: postgres:18
    profiles:
      - database
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-converso_whatsapp}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - converso-whatsapp-api-network
    expose:
      - "5432"

volumes:
  converso-whatsapp-api_instances:
  converso-whatsapp-api_redis:
  postgres_data:

networks:
  converso-whatsapp-api-network:
    name: converso-whatsapp-api-network
    driver: bridge
